/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 --types --keepnames --keepgroups --keepmeshes --transform public/models/casino_from_poly_by_google.glb 
Files: public/models/casino_from_poly_by_google.glb [729.01KB] > casino_from_poly_by_google-transformed.glb [125.85KB] (83%)
Author: IronEqual (https://sketchfab.com/ie-niels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/casino-from-poly-by-google-cc52937268914a919a6ee6330cd69036
Title: Casino from Poly by Google
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { CasinoInterface } from "../../../../hooks/helpers/useCasino";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
}


export default function CasinoFinished(
  props: JSX.IntrinsicElements["group"] & { casino?: CasinoInterface },
) {
  const { nodes, materials } = useGLTF("/models/casino_from_poly_by_google-transformed.glb") as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="casino_finished" position={[0, -0.096, 0]} scale={0.02}>
          <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial002} />
          <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial001} />
          <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial002} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/casino_from_poly_by_google-transformed.glb");
