[package]
cairo-version = "2.2.0"
name = "casino"
version = "0.0.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag="v0.3.3" }
eternum = { git = "https://github.com/BibliothecaDAO/eternum.git" }

[scripts]
katana = "katana"
deploy = "./scripts/deploy.sh"
time_travel = "./scripts/testing/advance_time.sh"
torii = "torii --world 0x62440ea5b77f1a4fad6e4a88383c750b9101a7bcc5d4de046dc0ae0628b6504"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/eternum2/katana"

## dev
#account_address = "0x74bfdb5562f91764fddbbf3f4fb322de114a00d6d6889b19a4dd7b45d5ba24d"
#private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

## prod
account_address = "0x4011e376fe0e8be617470fc8c3ccb11a0f88e383e42ed6af9d934f7d3af8091"
private_key = "0x7318b1bb2c88be4d85f7df34eed7f3bfcc396e7cadae945fe6465cf8f589055"
world_address = "0x4d79c99ce9b489b77461e3491970ea5ede1f1966f4d2ff65ee76cd8701d6dad"

[[target.dojo]]
build-external-contracts = [
    "eternum::models::*",
    "eternum::systems::*"
]